CREATE TABLE IF NOT EXISTS `asset_inspections` (
  `id` VARCHAR(36) NOT NULL,
  `organization_id` VARCHAR(36) NOT NULL,
  `return_line_id` VARCHAR(36) NOT NULL,
  `asset_id` VARCHAR(36) NOT NULL,
  `condition_status` ENUM('NEW', 'GOOD', 'FAIR', 'DAMAGED', 'CRITICAL') NOT NULL,
  `damage_classification` VARCHAR(255) NULL,
  `damage_severity` ENUM('NONE', 'MINOR', 'MODERATE', 'SEVERE') NOT NULL DEFAULT 'NONE',
  `chargeable_damage` BOOLEAN NOT NULL DEFAULT FALSE,
  `notes` TEXT NULL,
  `inspected_at` DATETIME(3) NOT NULL,
  `inspector_id` VARCHAR(36) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_asset_inspections_return_line` (`organization_id`, `return_line_id`),
  CONSTRAINT `fk_asset_inspections_org` FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_asset_inspections_return_line` FOREIGN KEY (`return_line_id`) REFERENCES `rental_return_lines`(`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_asset_inspections_asset` FOREIGN KEY (`asset_id`) REFERENCES `assets`(`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_asset_inspections_user` FOREIGN KEY (`inspector_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
